name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  x86_64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get secret key
      run: 'echo "$SECRET_KEY" > public.key'
      shell: bash
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
    - name: Build ipk
      run: ./build.sh https://downloads.openwrt.org/releases/19.07.7/targets/x86/64/openwrt-sdk-19.07.7-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz x86/64

    - name: Save ipk
      uses: actions/upload-artifact@v1
      with:
          name: x86_64
          path: target.zip
